# Generated by Django 4.1.5 on 2023-02-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('collection', '0006_remove_imagecollectionpage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecollection',
            name='tags',
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='imagecollection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageTag',
        ),
    ]
