# Generated by Django 4.1.5 on 2023-02-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepageheroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagegalleryimage',
            name='link',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
