# Generated by Django 4.1.5 on 2023-02-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagegalleryimage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagegalleryimage',
            name='title',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='homepagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homepagegalleryimage',
            name='link',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
