# Generated by Django 4.1.5 on 2023-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactpage_contactpageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact1',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact2',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
