# Generated by Django 4.1.5 on 2023-02-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0011_aboutpage_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
