# Generated by Django 4.1.5 on 2023-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_processpage_alter_aboutpage_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processpagephaseimage',
            name='phase',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
