# Generated by Django 4.1.5 on 2023-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_processpagephaseimage_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpagephaseimage',
            name='caption',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
