# Generated by Django 4.1.5 on 2023-02-02 17:43

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
