# Generated by Django 4.1.5 on 2023-02-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('portfolio', '0004_alter_portfoliopage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
